stages:
  classifier:
    cmd: python training/train_model.py --dataset training/dataset.ndjson --model package/model/logistic-regression.onnx
    deps:
      - training/train_model.py
      - training/dataset.ndjson
      - package/featurization.py
    outs:
      - package/model/logistic-regression.onnx
