stages:
  classifier:
    cmd: python training/train_model.py --dataset training/dataset.ndjson --model app/model/logistic-regression.onnx
    deps:
      - training/train_model.py
      - training/dataset.ndjson
      - app/featurization.py
    outs:
      - app/model/logistic-regression.onnx
